### ISSUE TITLE
Build error on 'make build'

### ISSUE THREAD

**Issue by ruyingzhe** [tkestack/tapp#3]
**Describe the bug**
I am following the guide [https://github.com/tkestack/tapp#build](url) to build, but on command `make build` and `make image` getting errors: 
```shell
~/gopath/src/tkestack.io/tapp]# make build
hack/build.sh
hack/build.sh: line 20: cd: /root/gopath/src/git.tencent.com/tke/tapp-controller: No such file or directory
make: *** [build] Error 1
```
```shell
~/gopath/src/tkestack.io/tapp]# make image
hack/verify-gofmt.sh
hack/build-image.sh
hack/build-image.sh: line 23: cd: /root/gopath/src/git.tencent.com/tke/tapp-controller: No such file or directory
make: *** [image] Error 1
```

**Environment**
 - OS: Linux VM_149_11_centos 3.10.107-1-tlinux2_kvm_guest-0049 #1 SMP Tue Jul 30 23:46:29 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
 - golang: go version go1.12.4 linux/amd64

**Comment by genedna** [comment]
The issue looks like caused by we changed the name from `tapp-controller` to `tapp` when the repo initiated.

Merge pull request #4
